spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    user: sa
    password: ""
    url: jdbc:h2:file:./data/testdb

server:
  port: ${PORT:8085}

app:
  auth:
    jwtSecret: e10a7f1b0764a203e8ccb959c0dd70d465ffa6289771ea192ad73a1b7a9916b25810369f093cc7f3f175ca5ed87844cde66ba9932fe3bfbfb0139623e70a75e7
    jwtExpirationMs: 900000
    jwtRefreshExpirationMs: 43200000

vk:
  api:
    version: 5.199
    url: https://api.vk.com
  app:
    secret-key: ${VK_APP_SECRET:}
    service-key: ${VK_SERVICE_KEY:}
  service:
    key: ${vk.app.service-key:}
  verify:
    maxSkewSeconds: 3600
  auth:
    enableServiceLogin: true
    enforceLaunchParams: false


frontend:
  url: ${FRONTEND_URL:http://localhost:4200}

yandex:
  api-key: ${YANDEX_API_KEY:}
  folder-id: ${YANDEX_FOLDER_ID:}